name: Deploy Worker

on:
  push:
    branches: [ "main" ]
    paths:
      - "cf-worker/**"
      - ".github/workflows/deploy-worker.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cf-worker
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: publish
        env:
          WRANGLER_LOG: debug
